version: "3"

services:
  proj:
    image: containous/whoami
    expose:
      - "80"
    networks:
      - default
      - linker
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.proj.rule=Host(`proj.domain.com`)"
      - "traefik.http.routers.proj.middlewares=test-redirectscheme@file"

  redis:
    image: "redis:alpine"

networks:
  linker:
    external: true
