version: "3"

services:
  dns:
    image: programster/dnsmasq
    expose:
      - "53/udp"
    ports:
      - "53:53/udp"
    networks:
      - linker
    volumes:
      - "./dnsmasq:/etc/dnsmasq.conf"

  traefik:
    container_name: traefik
    image: traefik:latest
    command: "--log.level=DEBUG"
    ports:
      - 80:80
      - 8080:8080
      - 4430:4430
      - 443:443
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./traefik:/etc/traefik
    networks:
      - linker

networks:
  linker:
    external: true
